-- Two-Learner Personalised Learning V2 has no shared starter library.
--
-- Max and Tia's learner-owned curricula are created by the production data
-- migration and curated through audited manifests. A clean local database is
-- intentionally schema-only so tests cannot accidentally depend on legacy
-- shared knowledge_items or retired category remapping helpers.
